name: Build
on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]
jobs:
  build_project:
    name: Release build and tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set script permissions
        run: chmod +x ./build-all.sh     
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Build projects
        run: ./build-all.sh 
      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            **/coverage/*
            !**/node_modules/**

  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    needs: [build_project]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download coverage reports
        uses: actions/download-artifact@v2
        with:
          name: coverage-reports
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
